### ISSUE TITLE
Suggestion: Soft Alpha

### ISSUE THREAD

**Issue by vicenterusso** [dreamcodestudio/UIMask#1]
Hi, great work!

Please check this URL below where I mention your repo and I suggest this inverse mask to the UI Extensions package. Can you consider adding soft masks to your shaders?

https://bitbucket.org/ddreaper/unity-ui-extensions/issues/30/feature-cutout-masks

**Comment by yapetrichka** [comment]
Hello, i will add soft mask on weekend.

**Comment by vicenterusso** [comment]
Awesome! Thanks!

How about the second item I wrote:
_"Can't isolate/group masks. Every object with Mask shader will make a hole on every object with Masked shader"_

Do you think there is something you can do about it?

**Comment by vicenterusso** [comment]
@slavaobninsk any news on soft mask?

**Comment by yapetrichka** [comment]
sorry, i now launch my game and don't have enought time to edit mask

**Comment by vicenterusso** [comment]
@slavaobninsk want to take a look at this now? :smile:

**Comment by yapetrichka** [comment]
only on next weekend
