### ISSUE TITLE
not work in android mobile

### ISSUE THREAD

**Issue by jiangzhen3s** [dreamcodestudio/UIMask#2]
hey
thanks great work first.
i find this shader not work in android mobile . is it right?

**Comment by yapetrichka** [comment]
hello maybe be can't test it on mobile devices, can you send me model of devices and android version

**Comment by jiangzhen3s** [comment]
thanks reply
i test in iphone5s work fine.
huawei ascend 1 android 4.0.3 can't work.
i am new shader programing,i can't fully understand your code 
can you recommend some shader book or blog  for me ?  i'm using unity3d focuse on mobible game development.
thank you very much.

**Comment by jiangzhen3s** [comment]
seems like not work in Unity3d UGUI

**Comment by yapetrichka** [comment]
For start you can read https://www.packtpub.com/game-development/unity-shaders-and-effects-cookbook

**Comment by jiangzhen3s** [comment]
thank you !!
