### ISSUE TITLE
Only Works in Editor Scene View, but not in Game View

### ISSUE THREAD

**Issue by C0nstan** [dreamcodestudio/UIMask#3]
Hi There,
I'm on Unity 5.3.4f1 and using the new UI System.
I have followed your Setup, but it doesnt work if i press Play. It just works in die Editor Scene View.
Any suggestions?

**Comment by yapetrichka** [comment]
Hello i test it in Unity 5.3.4 on weekend and link tutorial video for setting mask.

**Comment by MasterMeyer** [comment]
Actually, at first, i had that problem too, but when i set 'Clear Flags' of the camera to "Don't Clear" it worked

**Comment by vicenterusso** [comment]
It works only with **Screen Space - Overlay.** with the other 2 render mode this same problem happens

**Comment by Calvin2274** [comment]
Screen Space - Camera
http://puu.sh/oTLGo/754cdb3cfd.png

Screen Space - Overlay
http://puu.sh/oTLJ9/6a506828f4.png

But i do need to use camera as render mode because i have some 3D object need to be render in front of canvas UI, any suggestion ??

**Comment by CasperPas** [comment]
I have the same problem. Then I made it works again when I put 2 objects (Mask & Masked) in the same level, not parent-child as said the guide. The reason might be in the rendering order.

**Comment by JonathanGorr** [comment]
It works for me with screen space - camera, upon assigning the camera. This might be consolation to those using 5.4. This render mode cannot, however, overlap other UI elements using screen space - overlay, unfortunately, and I believe it's much less efficient. Fixing this would be greatly appreciated mister slavaobninsk. It's an awesome asset when working.

**Comment by yapetrichka** [comment]
Now it's works on all renders mode
![image](https://user-images.githubusercontent.com/7010398/233859721-419a2042-aa93-49fe-be8a-99aead6a4a49.png)
![image](https://user-images.githubusercontent.com/7010398/233859732-0aeedcee-ece8-4ae8-a3af-6a635190e50f.png)
![image](https://user-images.githubusercontent.com/7010398/233859749-e51a490f-3220-4590-bd9c-670c2452a597.png)

fixed on new component implementation
Released on next weekend

**Comment by yapetrichka** [comment]
https://github.com/dreamcodestudio/UIMask/releases/tag/v0.9.0
