### ISSUE TITLE
Put a license

### ISSUE THREAD

**Issue by Sushi271** [dreamcodestudio/UIMask#5]
To the author:

I can't find the license for this code. If you want anybody to be able to legally use it, please put an EULA file. Put it anyway, either telling straight that it's of limited use, or totally open source etc.

Nobody can use this code for now, as per this topic: https://softwareengineering.stackexchange.com/questions/148146/open-source-code-with-no-license-can-i-fork-it

**Comment by slavaobninsk** [comment]
MIT

**Comment by yapetrichka** [comment]
MIT
