### ISSUE TITLE
Animating image with ReverseMask not working (Unity 2017.4.2f2)

### ISSUE THREAD

**Issue by aerionTech** [dreamcodestudio/UIMask#6]
When animating the ReverseMask image by changing its width/height, it animates in the scene tab properly but not in the game tab. See this video:

https://drive.google.com/file/d/1smLNo_Heiz-UhJ3i_8Np-BhaTpBo5X3Z/view?usp=sharing

When not animating it, it works fine:
![unity_2018-06-06_14-41-49](https://user-images.githubusercontent.com/6082270/41017992-fdd9ce84-699a-11e8-85dc-efce3fc52710.png)

Here's an example project:
[CircleFadeTest.zip](https://github.com/slavaobninsk/UIMask/files/2075392/CircleFadeTest.zip)

**Comment by yapetrichka** [comment]
It's fixed on new component implementation
Released on next weekend

https://user-images.githubusercontent.com/7010398/233859368-515d50e1-4ddb-4437-8f8f-791be1542656.mp4

**Comment by yapetrichka** [comment]
https://github.com/dreamcodestudio/UIMask/releases/tag/v0.9.0
